/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MetaRouteImport } from './routes/meta'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SummonerGameNameTagLineRouteImport } from './routes/summoner.$gameName.$tagLine'

const MetaRoute = MetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SummonerGameNameTagLineRoute = SummonerGameNameTagLineRouteImport.update({
  id: '/summoner/$gameName/$tagLine',
  path: '/summoner/$gameName/$tagLine',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meta': typeof MetaRoute
  '/summoner/$gameName/$tagLine': typeof SummonerGameNameTagLineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meta': typeof MetaRoute
  '/summoner/$gameName/$tagLine': typeof SummonerGameNameTagLineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meta': typeof MetaRoute
  '/summoner/$gameName/$tagLine': typeof SummonerGameNameTagLineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/meta' | '/summoner/$gameName/$tagLine'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/meta' | '/summoner/$gameName/$tagLine'
  id: '__root__' | '/' | '/meta' | '/summoner/$gameName/$tagLine'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MetaRoute: typeof MetaRoute
  SummonerGameNameTagLineRoute: typeof SummonerGameNameTagLineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/meta': {
      id: '/meta'
      path: '/meta'
      fullPath: '/meta'
      preLoaderRoute: typeof MetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summoner/$gameName/$tagLine': {
      id: '/summoner/$gameName/$tagLine'
      path: '/summoner/$gameName/$tagLine'
      fullPath: '/summoner/$gameName/$tagLine'
      preLoaderRoute: typeof SummonerGameNameTagLineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MetaRoute: MetaRoute,
  SummonerGameNameTagLineRoute: SummonerGameNameTagLineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
